ktor:
  application:
    modules:
      - io.pii.game.ApplicationKt.module
  deployment:
    port: 8080
jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "Kokodi Card Game"
